package lunartools.ganimed.gui;

public enum SimpleEvents {
	EXIT,
	SAVEAS,
	MODEL_SELECTIONTYPECHANGED,
	MODEL_IMAGETYPECHANGED,
	MODEL_IMAGEFOLDERCHANGED,
	MODEL_IMAGESCHANGED,
	MODEL_IMAGESIZECHANGED,
	MODEL_ANIMPLAYBACKVALUESCHANGED,
	MODEL_ANIMBYTEARRAYCHANGED,
	MODEL_ANIMNUMBEROFIMAGESCHANGED,
	MODEL_REFRESH_SELECTION_GUI,
	MODEL_PNGOPTIONCHANGED;
}
