package lunartools.ganimed.gui;

public enum SimpleEvents {
	EXIT,
	SAVEGIF,
	MODEL_IMAGEFOLDERCHANGED,
	MODEL_IMAGESCHANGED,
	MODEL_IMAGESIZECHANGED,
	MODEL_GIFPLAYBACKVALUESCHANGED,
	MODEL_GIFBYTEARRAYCHANGED,
	MODEL_GIFNUMBEROFIMAGESCHANGED;
}
