package lunartools.ganimed.gui;

public enum SimpleEvents {
	EXIT,
	SAVEAS,
	MODEL_IMAGEFOLDERCHANGED,
	MODEL_IMAGESCHANGED,
	MODEL_IMAGESIZECHANGED,
	MODEL_ANIMPLAYBACKVALUESCHANGED,
	MODEL_ANIMBYTEARRAYCHANGED,
	MODEL_ANIMNUMBEROFIMAGESCHANGED;
}
